using System;
using System.Reflection;
using System.Text;
using CsAvroGen.DomainModel;

namespace holonsoft.CsAvroGen.Generator
{
    internal partial class AvroSchemaGenerator
    {
        private string CreateCommonHeader()
        {
            if (!_prgArgs.WriteCommentHeaderInAvroFile) return string.Empty;

            var sb = new StringBuilder();


            sb.Append(_indentProvider.Get());
            sb.Append("doc".ToDoubleQoutedString());
            sb.Append(": ");
            sb.AppendLine("// ------------------------------------------------------------------------------".ToDoubleQoutedString() + ", ");

            sb.Append(_indentProvider.Get());
            sb.Append("doc".ToDoubleQoutedString());
            sb.Append(": ");
            sb.AppendLine("// <auto-generated>".ToDoubleQoutedString() + ", ");

            sb.Append(_indentProvider.Get());
            sb.Append("doc".ToDoubleQoutedString());
            sb.Append(": ");
            sb.AppendLine(("//    Generated by holonsoft " + AppDomain.CurrentDomain.FriendlyName + " V" + Assembly.GetExecutingAssembly().AssemblyVersion().ToString()).ToDoubleQoutedString() + ", ");

            sb.Append(_indentProvider.Get());
            sb.Append("doc".ToDoubleQoutedString());
            sb.Append(": ");
            sb.AppendLine("//    Changes to this file may cause incorrect behavior and will be lost".ToDoubleQoutedString() + ", ");

            sb.Append(_indentProvider.Get());
            sb.Append("doc".ToDoubleQoutedString());
            sb.Append(": ");
            sb.AppendLine("//    if code is regenerated".ToDoubleQoutedString() + ", ");

            sb.Append(_indentProvider.Get());
            sb.Append("doc".ToDoubleQoutedString());
            sb.Append(": ");
            sb.AppendLine(("//    Generated at (UTC): " + DateTime.UtcNow.ToString("u")).ToDoubleQoutedString() + ", ");

            sb.Append(_indentProvider.Get());
            sb.Append("doc".ToDoubleQoutedString());
            sb.Append(": ");
            sb.AppendLine("// </auto-generated>".ToDoubleQoutedString() + ", ");

            sb.Append(_indentProvider.Get());
            sb.Append("doc".ToDoubleQoutedString());
            sb.Append(": ");
            sb.AppendLine("// ------------------------------------------------------------------------------".ToDoubleQoutedString() + ", ");

            sb.AppendLine("");

            return sb.ToString();
        }
    }
}